[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
opsepolia = "https://sepolia.optimism.io"

[profile.default.fmt]
line_length = 80
tab_width = 4
wrap_comments = true
bracket_spacing = true

